# Generated by Django 5.0 on 2023-12-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anouncement', '0002_alter_announcement_category_alter_announcement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='slug',
            field=models.SlugField(default='houssam', max_length=250, unique_for_date='created_at'),
        ),
    ]
