# Generated by Django 5.0 on 2023-12-19 18:39

import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anouncement', '0003_announcement_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelManagers(
            name='announcement',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveIndex(
            model_name='announcement',
            name='anouncement_created_81a894_idx',
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['-created_at'], name='anouncement_created_234a4e_idx'),
        ),
    ]
