# Generated by Django 5.0 on 2023-12-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anouncement', '0005_announcement_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='announcement',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='announcement',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Rejected'), (3, 'Published'), (4, 'Finished')], default=3),
        ),
    ]
